blank_issues_enabled: false
contact_links:
  - name: 📖 Project Documentation
    url: https://github.com/your-username/mahabharata-kosha/blob/main/README.md
    about: Please check the main project README for general information.
  - name: 🤔 Questions & Discussions
    url: https://github.com/your-username/mahabharata-kosha/discussions
    about: Please use GitHub Discussions for questions or broader conversations.