"""Initial migration

Revision ID: 4c0d2b053e47
Revises: 
Create Date: 2025-07-14 15:38:18.206193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0d2b053e47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parvas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_sanskrit', sa.String(length=255), nullable=False),
    sa.Column('title_english', sa.String(), nullable=False),
    sa.Column('parva_num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parva_num'),
    sa.UniqueConstraint('title_english'),
    sa.UniqueConstraint('title_sanskrit')
    )
    op.create_table('adhyayas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_sanskrit', sa.String(), nullable=False),
    sa.Column('title_english', sa.String(), nullable=False),
    sa.Column('adhyaya_num', sa.Integer(), nullable=False),
    sa.Column('parva_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parva_id'], ['parvas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shlokas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shloka_num', sa.Integer(), nullable=False),
    sa.Column('text_sanskrit', sa.Text(), nullable=False),
    sa.Column('text_english', sa.Text(), nullable=False),
    sa.Column('adhyaya_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adhyaya_id'], ['adhyayas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shlokas_id'), table_name='shlokas')
    op.drop_table('shlokas')
    op.drop_index(op.f('ix_adhyayas_id'), table_name='adhyayas')
    op.drop_table('adhyayas')
    op.drop_index(op.f('ix_parvas_id'), table_name='parvas')
    op.drop_table('parvas')
    # ### end Alembic commands ###
