"""enrich_shloka_model

Revision ID: 5dbe3be3e277
Revises: 4c0d2b053e47
Create Date: 2025-07-15 17:00:29.977363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dbe3be3e277'
down_revision: Union[str, Sequence[str], None] = '4c0d2b053e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shlokas', sa.Column('parva_num', sa.Integer(), nullable=False))
    op.add_column('shlokas', sa.Column('adhyaya_num', sa.Integer(), nullable=False))
    op.add_column('shlokas', sa.Column('pada_char', sa.Text(), nullable=False))
    op.add_column('shlokas', sa.Column('text_sanskrit_split', sa.Text(), nullable=True))
    
    # 1. Create the enum type first
    line_type_enum = sa.Enum('VERSE', 'PROSE', 'HEADER', name='line_type_enum')
    line_type_enum.create(op.get_bind(), checkfirst=True)
    
    # 2. Add the column using the enum
    op.add_column('shlokas', sa.Column('line_type', line_type_enum, nullable=False, server_default='VERSE'))
    
    op.add_column('shlokas', sa.Column('linguistic_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('shlokas', sa.Column('explanation_english', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('shlokas', sa.Column('explanation_marathi', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shlokas_id'), table_name='shlokas')
    op.drop_column('shlokas', 'explanation_marathi')
    op.drop_column('shlokas', 'explanation_english')
    op.drop_column('shlokas', 'linguistic_analysis')
    op.drop_column('shlokas', 'line_type')

    # Drop the enum type after removing the column
    line_type_enum = sa.Enum('VERSE', 'PROSE', 'HEADER', name='line_type_enum')
    line_type_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_column('shlokas', 'text_sanskrit_split')
    op.drop_column('shlokas', 'pada_char')
    op.drop_column('shlokas', 'adhyaya_num')
    op.drop_column('shlokas', 'parva_num')
    op.drop_index(op.f('ix_parvas_id'), table_name='parvas')
    op.drop_index(op.f('ix_adhyayas_id'), table_name='adhyayas')
    # ### end Alembic commands ###
