"""enrich_shloka_model

Revision ID: ddead149437b
Revises: 4c0d2b053e47
Create Date: 2025-07-15 16:21:00.960765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddead149437b'
down_revision: Union[str, Sequence[str], None] = '4c0d2b053e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_adhyayas_id'), 'adhyayas', ['id'], unique=False)
    op.create_index(op.f('ix_parvas_id'), 'parvas', ['id'], unique=False)
    op.add_column('shlokas', sa.Column('parva_num', sa.Integer(), nullable=False))
    op.add_column('shlokas', sa.Column('adhyaya_num', sa.Integer(), nullable=False))
    op.add_column('shlokas', sa.Column('pada_char', sa.Text(), nullable=False))
    op.add_column('shlokas', sa.Column('text_sanskrit_split', sa.Text(), nullable=True))
    op.add_column('shlokas', sa.Column('line_type', sa.String(length=50), nullable=False))
    op.add_column('shlokas', sa.Column('linguistic_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('shlokas', sa.Column('explanation_english', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('shlokas', sa.Column('explanation_marathi', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_shlokas_id'), 'shlokas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shlokas_id'), table_name='shlokas')
    op.drop_column('shlokas', 'explanation_marathi')
    op.drop_column('shlokas', 'explanation_english')
    op.drop_column('shlokas', 'linguistic_analysis')
    op.drop_column('shlokas', 'line_type')
    op.drop_column('shlokas', 'text_sanskrit_split')
    op.drop_column('shlokas', 'pada_char')
    op.drop_column('shlokas', 'adhyaya_num')
    op.drop_column('shlokas', 'parva_num')
    op.drop_index(op.f('ix_parvas_id'), table_name='parvas')
    op.drop_index(op.f('ix_adhyayas_id'), table_name='adhyayas')
    # ### end Alembic commands ###
